# Generated by Django 3.0 on 2019-12-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
