# Generated by Django 3.0 on 2019-12-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userinfo_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='phone',
            new_name='photo',
        ),
    ]
